services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SUDHAUS7\Xlsimport\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Dto/*'

  SUDHAUS7\Xlsimport\Controller\DataSheetImportController:
    public: true

  SUDHAUS7\Xlsimport\Service\ImportService:
    public: true
