name: tests11

on:
  workflow_dispatch:

jobs:
  dummy:
    name: "dummy v11 (disabled on master) to allow creation of badges for other branches"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
